# Generated by Django 4.1.5 on 2023-03-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizrecord',
            name='marks_obtained',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quizrecord',
            name='right_answer_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quizrecord',
            name='wrong_answer_count',
            field=models.PositiveIntegerField(),
        ),
    ]
